server:
  port: 9999
  servlet:
    context-path: /infinite-admin
spring:
  profiles:
    active: dev
  application:
    name: infinite-admin
  cloud:
    #nacos 注册中心
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: #nacos namespace
    sentinel:
      enabled: true
      eager: true
      transport:
        dashboard: 127.0.0.1:7070
      filter:
        url-patterns: /**
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    user:
      name: root
      password: Admin&20200804
      roles: ADMIN
  main:
    allow-bean-definition-overriding: true #后发现的bean会覆盖之前相同名称的bean
logging:
  level:
    root: info                          #DEBUG,INFO,WARN,ERROR
    org.springframework.security: info
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://127.0.0.1:8848
  cloud:
    subscribed-services: dubbo-infinite-admin
  consumer:
    check: false #close to subscribe services which check or not automatically
  application:
    name: infinite-admin
    qos-enable: false
    qos-accept-foreign-ip: false
infinite:
  jwt:
    secret: WoJf6Mi1laQp7vHuIHSvcg==
    expiration: 604800 # token有效时长，7天，单位秒
    header: Authorization