server:
  port: 9999
  undertow:
    buffer-size: 1024 # 每块buffer的空间大小,越小的空间被利用越充分
    direct-buffers: true # 是否分配的直接内存(NIO直接分配的堆外内存)
    threads:
      worker: 256
      io: 16
  servlet:
    context-path: /infinite-admin
spring:
  profiles:
    active: dev
  application:
    name: admin-app
  cloud:
    #nacos 注册中心
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    user:
      name: root
      password: Admin&20200804
      roles: admin
logging:
  level:
    root: info                          #DEBUG,INFO,WARN,ERROR
    org.springframework.security: info
dubbo:
  registry:
    address: spring-cloud://127.0.0.1:8848
  cloud:
    subscribed-services: ''
infinite:
  jwt:
    secret: WoJf6Mi1laQp7vHuIHSvcg==
    expiration: 604800 # token有效时长，7天，单位秒
    header: token