spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #support JDBC4
    url: jdbc:mysql://127.0.0.1:3306/infinite_admin?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&
      rewriteBatchedStatements=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 10           #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      maximum-pool-size: 20      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      idle-timeout: 500000       #空闲连接超时时间，默认值600000（10分钟）
      max-lifetime: 540000       #连接最大存活时间，不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      connection-timeout: 60000  #连接超时时间：毫秒，小于250毫秒，否则被重置为默认值30秒
      auto-commit: true
      pool-name: HikariCPDataSource
  #    schema: classpath:db/admin_schema.sql
#    data: classpath:db/admin_data.sql